//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto_trade
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyOrders
    {
        public int id { get; set; }
        public Nullable<int> market_id { get; set; }
        public string order_uuid { get; set; }
        public string order_type { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> quantity_remain { get; set; }
        public Nullable<decimal> reserved { get; set; }
        public Nullable<decimal> reserved_remaining { get; set; }
        public Nullable<decimal> commission_reserved { get; set; }
        public Nullable<decimal> commission_reserved_remaining { get; set; }
        public Nullable<decimal> commission_paid { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> opened_at { get; set; }
        public Nullable<System.DateTime> closed_at { get; set; }
    }
}
